---
- name: Ansible playbook to run yolo e-commerce docker containers using ansible
  hosts: all
  become: true
  roles: 
    - frontend-deployment
    - setup-mongodb   
    - backend-deployment
    