# ansible/roles/mongodb/tasks/main.yml
---
- name: Pull MongoDB Docker image
  docker_image:
    name: mongo
    tag: latest
    source: pull
  tags:
    - database
    - backend

- name: Run MongoDB Container
  docker_container:
    name: "{{ mongo_container_name }}"
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - "{{ mongo_volume }}:/data/db"
    networks:
      - name: "{{ mongo_network }}"
    restart_policy: always
  tags:
    - database
    - backend
