apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: perischepkemoi/yolo-backend:v1.0.3
        ports:
        - containerPort: 5000
        env:
          - name: MONGODB_URI
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: MONGO_URL
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
