---
# tasks file for setup-backend

- name: Pull image from repository
  docker_image:
    name: "{{ backend_image }}"
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: "{{ backend_container_name }}"
    image: "{{ backend_image }}"
    networks:
      - name: "{{ backend_network }}"
    ports:
      - "{{ item }}"
    command: "{{ backend_command }}"
  become: yes
  loop: "{{ backend_ports }}"
